#!/usr/bin/env python3
"""
render_system_map.py - the TAKTO signal map on the profile README.

Hand-drawn rather than generated by a diagram library, for the same reason the
repo headers are: a stock flowchart renderer picks its own shapes, spacing and
palette, and it shows. This draws the actual topology, labels the actual buses,
and keeps one accent for the one thing worth following, the tendon path closing
back onto the hand the encoders are measuring.

Light and dark variants, selected by prefers-color-scheme. No script, no external
references, no web fonts.

Usage: python3 render_system_map.py
"""

from pathlib import Path

W, H = 1000, 316
MONO = ('font-family="ui-monospace,SFMono-Regular,SF Mono,Menlo,'
        'Consolas,monospace"')

THEMES = {
    "light": dict(ink="#191713", muted="#6e6b62", line="#b9b3a3",
                  faint="#ddd8ca", accent="#d94e12", fill="#f6f4ef",
                  panel="#efece4"),
    "dark":  dict(ink="#f0ede6", muted="#8f887c", line="#544d43",
                  faint="#38332c", accent="#ff7a3d", fill="#1a1714",
                  panel="#161310"),
}


def n(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def txt(x, y, s, fill, size=11, anchor="start", ls=1.1, weight=None):
    w = f' font-weight="{weight}"' if weight else ""
    return (f'<text x="{n(x)}" y="{n(y)}" {MONO} font-size="{size}" '
            f'letter-spacing="{ls}" text-anchor="{anchor}" fill="{fill}"{w}>'
            f'{s}</text>')


def block(x, y, w, h, c, lines, accent=False, sub=None):
    col = c["accent"] if accent else c["line"]
    o = [f'<rect x="{n(x)}" y="{n(y)}" width="{n(w)}" height="{n(h)}" rx="3" '
         f'fill="{c["fill"]}" stroke="{col}" stroke-width="{1.6 if accent else 1.2}"/>']
    cy = y + h / 2 - (len(lines) - 1) * 8
    for i, ln in enumerate(lines):
        strong = i == 0
        o.append(txt(x + w / 2, cy + i * 16 + 4, ln,
                     c["accent"] if (accent and strong) else
                     (c["ink"] if strong else c["muted"]),
                     11 if strong else 9.5, "middle", 1.0 if strong else 0.8))
    if sub:
        o.append(txt(x + w / 2, y + h + 14, sub, c["faint"], 8.5, "middle", 1.0))
    return "".join(o)


def build(theme):
    c = THEMES[theme]
    mid, mida = f'm{theme}', f'ma{theme}'
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
         f'width="{W}" height="{H}" fill="none" role="img" '
         f'aria-label="Signal map of the TAKTO system. Twelve AS5600 joint '
         f'encoders behind two multiplexers, two BNO085 IMUs and one EMG channel '
         f'feed a Teensy 4.1, which streams over USB serial to a host PC. The '
         f'host owns the motor bus through a U2D2 and drives Dynamixel XC330 '
         f'servos on tendon spools, whose tendons close the loop back onto the '
         f'worn hand. The host also feeds the web console, the AR layer and the '
         f'Android app.">',
         f'<defs>'
         f'<marker id="{mid}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" '
         f'markerHeight="6" orient="auto">'
         f'<path d="M0 1L7 4L0 7z" fill="{c["line"]}"/></marker>'
         f'<marker id="{mida}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" '
         f'markerHeight="7" orient="auto">'
         f'<path d="M0 1L7 4L0 7z" fill="{c["accent"]}"/></marker>'
         f'</defs>']

    # worn enclosure
    o.append(f'<rect x="8" y="44" width="228" height="216" rx="4" '
             f'fill="{c["panel"]}" stroke="{c["faint"]}" stroke-width="1" '
             f'stroke-dasharray="3 3"/>')
    o.append(txt(16, 60, "WORN", c["muted"], 9, "start", 2.0))

    # sensing blocks
    o.append(block(20, 70, 204, 52, c,
                   ["12 x AS5600", "joint encoders, 2 x TCA9548A"]))
    o.append(block(20, 134, 204, 52, c,
                   ["2 x BNO085", "hand + forearm, separate buses"]))
    o.append(block(20, 198, 204, 44, c, ["1 x EMG channel"]))

    # sensing spine into the Teensy
    o.append(f'<path d="M224 96H250M224 160H250M224 220H250" '
             f'stroke="{c["line"]}" stroke-width="1.2"/>')
    o.append(f'<path d="M250 96V220" stroke="{c["line"]}" stroke-width="1.2"/>')
    o.append(f'<path d="M250 158H300" stroke="{c["line"]}" stroke-width="1.2" '
             f'marker-end="url(#{mid})"/>')
    o.append(txt(258, 150, "I2C", c["muted"], 8.5))

    # acquisition and host
    o.append(block(306, 126, 164, 68, c, ["Teensy 4.1", "acquisition, SD log"]))
    o.append(f'<path d="M470 160H540" stroke="{c["line"]}" stroke-width="1.2" '
             f'marker-end="url(#{mid})"/>')
    o.append(txt(505, 152, "USB serial", c["muted"], 8.5, "middle"))
    o.append(block(546, 126, 164, 68, c, ["host PC", "control loop"]))

    # host -> motors (up), host -> surfaces (down)
    o.append(f'<path d="M710 146H752V96H786" stroke="{c["line"]}" '
             f'stroke-width="1.2" marker-end="url(#{mid})"/>')
    o.append(txt(746, 100, "U2D2 &#183; Protocol 2.0", c["muted"], 8.5, "end"))
    o.append(f'<path d="M710 174H752V222H786" stroke="{c["line"]}" '
             f'stroke-width="1.2" marker-end="url(#{mid})"/>')

    o.append(block(792, 70, 192, 52, c, ["2 x XC330", "tendon spools"],
                   accent=True))
    o.append(block(792, 190, 192, 64, c,
                   ["web console", "AR layer &#183; Android"]))

    # the tendon closing the loop back onto the worn hand
    o.append(f'<path d="M888 70V26H122V64" stroke="{c["accent"]}" '
             f'stroke-width="1.8" marker-end="url(#{mida})"/>')
    o.append(f'<rect x="452" y="16" width="106" height="20" rx="3" '
             f'fill="{c["fill"]}"/>')
    o.append(txt(505, 30, "TENDON", c["accent"], 9.5, "middle", 1.8))

    o.append(txt(8, 300, "THE HOST OWNS THE MOTOR BUS &#183; THE TEENSY ONLY "
                 "SENSES", c["muted"], 9.5, "start", 1.3))
    o.append('</svg>')
    return "".join(o)


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    for t in ("light", "dark"):
        f = here / f"system-map-{t}.svg"
        f.write_text(build(t), encoding="utf-8")
        print(f"{f.name}  {f.stat().st_size / 1024:.1f} KB")
