#!/usr/bin/env python3
"""
render_system_map.py - the TAKTO ONE signal map on the profile README.

Hand-drawn rather than generated by a diagram library, for the same reason the
repo headers are: a stock flowchart renderer picks its own shapes, spacing and
palette, and it shows.

The topology is the one in Fable/ECOSYSTEM.md: sensing into a Teensy, a single
host that owns both the motor bus and the wire contract, and three synchronised
client surfaces hanging off one WebSocket. One accent, spent on the tendon path
closing back onto the hand the encoders are measuring.

Light and dark variants, selected by prefers-color-scheme. No script, no external
references, no web fonts.

Usage: python3 render_system_map.py
"""

from pathlib import Path

W, H = 1000, 372
MONO = ('font-family="ui-monospace,SFMono-Regular,SF Mono,Menlo,'
        'Consolas,monospace"')

THEMES = {
    "light": dict(ink="#191713", muted="#6e6b62", line="#b9b3a3",
                  faint="#ddd8ca", accent="#d94e12", fill="#f6f4ef",
                  panel="#efece4"),
    "dark":  dict(ink="#f0ede6", muted="#8f887c", line="#544d43",
                  faint="#38332c", accent="#ff7a3d", fill="#1a1714",
                  panel="#161310"),
}


def n(v):
    return f"{v:.1f}".rstrip("0").rstrip(".")


def txt(x, y, s, fill, size=11, anchor="start", ls=1.1):
    return (f'<text x="{n(x)}" y="{n(y)}" {MONO} font-size="{size}" '
            f'letter-spacing="{ls}" text-anchor="{anchor}" fill="{fill}">{s}</text>')


def block(x, y, w, h, c, lines, accent=False):
    col = c["accent"] if accent else c["line"]
    o = [f'<rect x="{n(x)}" y="{n(y)}" width="{n(w)}" height="{n(h)}" rx="3" '
         f'fill="{c["fill"]}" stroke="{col}" '
         f'stroke-width="{1.6 if accent else 1.2}"/>']
    top = y + h / 2 - (len(lines) - 1) * 8
    for i, ln in enumerate(lines):
        head = i == 0
        o.append(txt(x + w / 2, top + i * 16 + 4, ln,
                     c["accent"] if (accent and head) else
                     (c["ink"] if head else c["muted"]),
                     11 if head else 9.5, "middle", 1.0 if head else 0.8))
    return "".join(o)


def build(theme):
    c = THEMES[theme]
    mid, mida = f'm{theme}', f'ma{theme}'
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}" '
         f'width="{W}" height="{H}" fill="none" role="img" '
         f'aria-label="Signal map of the TAKTO ONE system. Twelve AS5600 joint '
         f'encoders behind two multiplexers, two BNO085 IMUs and one EMG channel '
         f'feed a Teensy 4.1 over I2C. The Teensy streams over USB serial to a '
         f'host bridge, which owns the motor bus through a U2D2 and drives two '
         f'Dynamixel XC330 servos on tendon spools, whose tendons close the loop '
         f'back onto the worn hand. The same host serves one WebSocket contract '
         f'to three synchronised surfaces: a web console, an AR headset layer '
         f'called LUMEN, and an Android companion app.">',
         f'<defs>'
         f'<marker id="{mid}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" '
         f'markerHeight="6" orient="auto">'
         f'<path d="M0 1L7 4L0 7z" fill="{c["line"]}"/></marker>'
         f'<marker id="{mida}" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="7" '
         f'markerHeight="7" orient="auto">'
         f'<path d="M0 1L7 4L0 7z" fill="{c["accent"]}"/></marker>'
         f'</defs>']

    # ---- worn hardware -----------------------------------------------------
    o.append(f'<rect x="8" y="44" width="228" height="216" rx="4" '
             f'fill="{c["panel"]}" stroke="{c["faint"]}" stroke-width="1" '
             f'stroke-dasharray="3 3"/>')
    o.append(txt(16, 60, "WORN", c["muted"], 9, "start", 2.0))
    o.append(block(20, 70, 204, 52, c,
                   ["12 x AS5600", "joint encoders, 2 x TCA9548A"]))
    o.append(block(20, 134, 204, 52, c,
                   ["2 x BNO085", "hand + forearm, separate buses"]))
    o.append(block(20, 198, 204, 44, c, ["1 x EMG channel"]))

    o.append(f'<path d="M224 96H250M224 160H250M224 220H250" '
             f'stroke="{c["line"]}" stroke-width="1.2"/>')
    o.append(f'<path d="M250 96V220" stroke="{c["line"]}" stroke-width="1.2"/>')
    o.append(f'<path d="M250 160H300" stroke="{c["line"]}" stroke-width="1.2" '
             f'marker-end="url(#{mid})"/>')
    o.append(txt(258, 152, "I2C", c["muted"], 8.5))

    # ---- acquisition and host ---------------------------------------------
    o.append(block(306, 126, 150, 68, c, ["Teensy 4.1", "acquisition, SD log"]))
    o.append(f'<path d="M456 160H514" stroke="{c["line"]}" stroke-width="1.2" '
             f'marker-end="url(#{mid})"/>')
    o.append(txt(485, 152, "USB serial", c["muted"], 8.5, "middle"))
    o.append(block(520, 126, 180, 68, c, ["host bridge", "control loop"]))

    # ---- motor bus ---------------------------------------------------------
    o.append(f'<path d="M610 126V70H754" stroke="{c["line"]}" stroke-width="1.2" '
             f'marker-end="url(#{mid})"/>')
    o.append(txt(620, 62, "U2D2 &#183; Protocol 2.0", c["muted"], 8.5))
    o.append(block(760, 44, 200, 52, c, ["2 x XC330", "tendon spools"],
                   accent=True))

    # the tendon closing the loop back onto the hand
    o.append(f'<path d="M860 44V22H122V64" stroke="{c["accent"]}" '
             f'stroke-width="1.8" marker-end="url(#{mida})"/>')
    o.append(f'<rect x="438" y="12" width="106" height="20" rx="3" '
             f'fill="{c["fill"]}"/>')
    o.append(txt(491, 26, "TENDON", c["accent"], 9.5, "middle", 1.8))

    # ---- the three client surfaces ----------------------------------------
    o.append(f'<path d="M700 176H736V300" stroke="{c["line"]}" '
             f'stroke-width="1.2"/>')
    for y in (164, 226, 288):
        o.append(f'<path d="M736 {y}H754" stroke="{c["line"]}" '
                 f'stroke-width="1.2" marker-end="url(#{mid})"/>')
    o.append(f'<path d="M736 176V300" stroke="{c["line"]}" stroke-width="1.2"/>')

    o.append(block(760, 140, 200, 48, c, ["web console", ":8096"]))
    o.append(block(760, 202, 200, 48, c, ["AR headset", "LUMEN &#183; :8097"]))
    o.append(block(760, 264, 200, 48, c, ["Android app", "companion, pairs by QR"]))

    o.append(txt(610, 212, "ws :8765", c["muted"], 8.5, "middle", 0.9))

    # ---- captions ----------------------------------------------------------
    o.append(txt(8, 296, "THE HOST OWNS THE MOTOR BUS", c["muted"], 9.5,
                 "start", 1.3))
    o.append(txt(8, 314, "THE TEENSY ONLY SENSES", c["muted"], 9.5, "start", 1.3))
    o.append(txt(8, 350, "ONE HOST &#183; THREE SYNCHRONISED SURFACES &#183; "
                 "ONE CONTRACT", c["faint"], 9.5, "start", 1.3))
    o.append('</svg>')
    return "".join(o)


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    for t in ("light", "dark"):
        f = here / f"system-map-{t}.svg"
        f.write_text(build(t), encoding="utf-8")
        print(f"{f.name}  {f.stat().st_size / 1024:.1f} KB")
